#!/usr/bin/env node
import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const repoRoot = join(__dirname, '..');
const distDir = join(repoRoot, 'dist');
const { tokens } = await import('../dist/tokens/src/index.js');

function flattenObject(obj, prefix = '') {
  const result = {};
  for (const [key, value] of Object.entries(obj)) {
    const cssVarName = prefix ? `${prefix}-${key}` : key;
    if (typeof value === 'string') {
      result[cssVarName] = value;
    } else if (typeof value === 'object' && value !== null) {
      Object.assign(result, flattenObject(value, cssVarName));
    }
  }
  return result;
}

const cssVars = flattenObject(tokens, 'token');
const lines = ['/* Auto-generated by generate-css.mjs - DO NOT EDIT */', ':root {'];
for (const [name, value] of Object.entries(cssVars)) {
  lines.push(`  --${name}: ${value};`);
}
lines.push('}');
mkdirSync(distDir, { recursive: true });
writeFileSync(join(distDir, 'tokens.css'), `${lines.join('\n')}\n`);
console.log('Generated dist/tokens.css');
